package com.addbk.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.addbk.bean.Login;
import com.addbk.helper.ConnectionFactory;

public class LoginDaoService implements ILoginDao {

	// query to insert
	private static String CREATE_USER = "INSERT INTO loginaddress (username,password,isactive) VALUES (?,?,?)";

	// search login
	private static String SEARCH_USER = "SELECT * FROM loginaddress WHERE username=? AND password=? AND isactive='Y'";

	// creating object for Connection
	private Connection connection = null;

	// creating object for PreparedStatement
	private PreparedStatement statement = null;

	// creating object for ResultSet
	private ResultSet resultSet = null;

	// method to insert
	/* (non-Javadoc)
	 * @see com.addbk.dao.ILoginDao#insert(com.addbk.bean.Login)
	 */
	@Override
	public int insert(Login objLogin) {

		// local variable
		int logId = 0;

		try {
			// connection
			connection = ConnectionFactory.getConnection();

			// passing autogenerate column name
			String generateColumn[] = { "logid" };
			// passing insert query
			statement = connection
					.prepareStatement(CREATE_USER, generateColumn);
			// setting vales
			statement.setString(1, objLogin.getUserName());
			statement.setString(2, objLogin.getPassword());
			statement.setString(3, "Y");

			// execute query
			statement.executeUpdate();

			// getting generatedKey
			resultSet = statement.getGeneratedKeys();

			if (resultSet.next()) {
				// getting autogenerated key
				logId = resultSet.getInt(1);
			}

		} catch (Exception e) {
			System.out.println(e);
		} finally {
			try {
				// close
				statement.close();
				connection.close();
			} catch (SQLException e) {
				System.out.println(e);
			}
		}
		return logId;
	}

	// method to search login
	/* (non-Javadoc)
	 * @see com.addbk.dao.ILoginDao#search(java.lang.String, java.lang.String)
	 */
	@Override
	public Login search(String userName, String password) {

		// creating object for Login
		Login objLogin = null;

		try {

			// connection
			connection = ConnectionFactory.getConnection();

			// passing insert query
			statement = connection.prepareStatement(SEARCH_USER);

			// setting vales
			statement.setString(1, userName);
			statement.setString(2, password);

			// executing query
			resultSet = statement.executeQuery();

			if (resultSet.next()) {

				// reading data
				int logId = resultSet.getInt("logid");
				String urName = resultSet.getString("username");
				String pass = resultSet.getString("password");

				// initializing Login
				objLogin = new Login(logId, urName, pass);

			}

		} catch (Exception e) {
			System.out.println(e);
		} finally {
			try {

				// close
				resultSet.close();
				statement.close();
				connection.close();
			} catch (SQLException e) {
				System.out.println(e);
			}

		}

		return objLogin;

	}
}
